import {NextRequest,NextResponse} from 'next/server'
import {z} from 'zod'
import {getAuthenticatedClub} from '../../../lib/supabase-server'

const createSchema=z.object({name:z.string().trim().min(3).max(160),description:z.string().trim().max(500).nullable(),testIds:z.array(z.string().uuid()).min(1).max(50)})
const updateSchema=z.object({id:z.string().uuid(),active:z.boolean()})

async function admin(){const context=await getAuthenticatedClub();if(context.error||!context.clubId||!context.user)return{...context,allowed:false};const {data}=await context.supabase.from('perfiles').select('rol').eq('id',context.user.id).eq('club_id',context.clubId).maybeSingle();return{...context,allowed:['administrador','administrador_organizacion'].includes(String(data?.rol).toLowerCase())}}

export async function POST(request:NextRequest){const input=createSchema.safeParse(await request.json().catch(()=>({})));if(!input.success)return NextResponse.json({error:'Batería inválida',details:input.error.flatten()},{status:400});const context=await admin();if(!context.allowed||!context.clubId||!context.user)return NextResponse.json({error:'Solo administración puede gestionar baterías'},{status:403});const testIds=[...new Set(input.data.testIds)];const {data:tests}=await context.supabase.from('catalogo_pruebas_fisicas').select('id').in('id',testIds).eq('activo',true).or(`club_id.is.null,club_id.eq.${context.clubId}`);if((tests||[]).length!==testIds.length)return NextResponse.json({error:'Una o más pruebas no están disponibles para la organización'},{status:400});const {data:battery,error}=await context.supabase.from('baterias_pruebas_fisicas').insert({club_id:context.clubId,nombre:input.data.name,descripcion:input.data.description,created_by:context.user.id}).select('id').single();if(error)return NextResponse.json({error:error.message},{status:400});const items=testIds.map((testId,index)=>({bateria_id:battery.id,prueba_id:testId,orden:index,requerida:true}));const itemResult=await context.supabase.from('bateria_pruebas_items').insert(items);if(itemResult.error){await context.supabase.from('baterias_pruebas_fisicas').delete().eq('id',battery.id).eq('club_id',context.clubId);return NextResponse.json({error:itemResult.error.message},{status:400})}return NextResponse.json({battery},{status:201})}

export async function PATCH(request:NextRequest){const input=updateSchema.safeParse(await request.json().catch(()=>({})));if(!input.success)return NextResponse.json({error:'Cambio inválido'},{status:400});const context=await admin();if(!context.allowed||!context.clubId)return NextResponse.json({error:'No autorizado'},{status:403});const {data,error}=await context.supabase.from('baterias_pruebas_fisicas').update({activa:input.data.active}).eq('id',input.data.id).eq('club_id',context.clubId).select('id').maybeSingle();if(error)return NextResponse.json({error:error.message},{status:400});if(!data)return NextResponse.json({error:'Batería no encontrada'},{status:404});return NextResponse.json({battery:data})}
