import Link from 'next/link'
import EvidenceManager from '../../../../components/gymnasts/EvidenceManager'
import FeedbackTimeline from '../../../../components/gymnasts/FeedbackTimeline'
import {getEvidenceWorkspace} from '../../../../lib/gymnasts/server'

export default async function EvidencePage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{pagina?:string}>}){
  const [{id},query]=await Promise.all([params,searchParams]);const data=await getEvidenceWorkspace(id,Number(query.pagina)||1)
  const elements=data.elements.map(x=>({id:String(x.id),name:String(x.nombre)}));const sessions=data.sessions.map(x=>({id:String(x.id),name:`${String(x.fecha_calendario)} · ${String(x.objetivo)}`}))
  const relatedName=(value:unknown)=>{const item=Array.isArray(value)?value[0]:value;return typeof item==='object'&&item!==null&&'nombre' in item?String(item.nombre):null}
  return <div className="mx-auto max-w-7xl space-y-10"><header><p className="text-xs font-black uppercase tracking-widest text-indigo-600">Evidencia y aprendizaje</p><h2 className="text-2xl font-black">Videos, imágenes y retroalimentación</h2><p className="text-sm text-slate-500">Los enlaces son firmados, temporales y no exponen públicamente los archivos.</p></header><EvidenceManager gymnastId={id} elements={elements} sessions={sessions} evidence={data.evidence.map(x=>({id:String(x.id),url:x.signedUrl,mime:String(x.mime_type),moment:typeof x.momento==='string'?x.momento:null,comment:typeof x.comentario==='string'?x.comentario:null,privacy:String(x.privacidad),createdAt:String(x.created_at),representativeFrame:x.frame_representativo_segundos===null?null:Number(x.frame_representativo_segundos)}))}/>{data.totalPages>1&&<nav aria-label="Paginación de evidencias" className="flex items-center justify-center gap-3"><Link aria-disabled={data.page===1} href={`?pagina=${Math.max(1,data.page-1)}`} className="rounded-lg border px-3 py-2 text-sm font-bold aria-disabled:pointer-events-none aria-disabled:opacity-40">Anterior</Link><span className="text-sm font-bold">Página {data.page} de {data.totalPages} · {data.total} evidencias</span><Link aria-disabled={data.page===data.totalPages} href={`?pagina=${Math.min(data.totalPages,data.page+1)}`} className="rounded-lg border px-3 py-2 text-sm font-bold aria-disabled:pointer-events-none aria-disabled:opacity-40">Siguiente</Link></nav>}<FeedbackTimeline gymnastId={id} elements={elements} sessions={sessions} entries={data.feedback.map(x=>({id:String(x.id),date:String(x.created_at).slice(0,10),element:relatedName(x.elementos_tecnicos),comment:typeof x.comentario_entrenador==='string'?x.comentario_entrenador:null,cue:typeof x.indicacion_tecnica==='string'?x.indicacion_tecnica:null,explanation:typeof x.explicacion==='string'?x.explicacion:null,perception:typeof x.percepcion_gimnasta==='string'?x.percepcion_gimnasta:null,understanding:x.nivel_comprension===null?null:Number(x.nivel_comprension),nextFocus:String(x.proximo_foco||''),family:Boolean(x.visible_familia)}))}/></div>
}
