import Link from 'next/link'
import {getIndividualReport} from '../../../../../lib/gymnasts/server'

export default async function FamilyReportPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const data=await getIndividualReport(id);const group=relation(data.gymnast.grupos);const authorizedFeedback=data.feedback.filter(item=>Boolean(item.visible_familia))
  return <div className="mx-auto max-w-5xl space-y-6 print:max-w-none"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-emerald-700">Informe autorizado para familia</p><h1 className="text-3xl font-black">{String(data.gymnast.nombre)}</h1><p className="text-sm text-slate-500">{String(group.nombre||'Grupo')} · nivel {String(group.nivel||'—')} · {new Intl.DateTimeFormat('es-CO',{dateStyle:'long',timeZone:'America/Bogota'}).format(new Date())}</p></div><div className="flex gap-2 print:hidden"><Link href="../" className="rounded-xl border px-4 py-2 text-sm font-bold">Volver al informe técnico</Link><button onClick={undefined} className="hidden" aria-hidden="true"/></div></header><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">Esta versión utiliza lenguaje comprensible y excluye restricciones, notas internas, comparaciones con otras gimnastas y retroalimentaciones no autorizadas.</div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Asistencia" value={data.metrics.attendancePercent===null?'Sin datos':`${data.metrics.attendancePercent}%`}/><Metric label="Objetivos activos" value={String(data.goals.goals.filter(goal=>['pendiente','en_progreso','en_riesgo'].includes(String(goal.estado))).length)}/><Metric label="Competencias previstas" value={String(data.competitions.assigned.length)}/></div><Section title="Progreso técnico"><ul className="space-y-2">{data.technical.assessments.slice(0,12).map(row=><li key={String(row.id)} className="flex justify-between gap-4 border-b pb-2 text-sm"><span className="font-bold">{name(row.elementos_tecnicos)}</span><span>{String(row.porcentaje_dominio)}% · {name(row.catalogo_items).replaceAll('_',' ')}</span></li>)}</ul></Section><Section title="Objetivos"><ul className="space-y-2">{data.goals.goals.map(goal=><li key={String(goal.id)} className="text-sm"><b>{String(goal.descripcion)}</b> — avance {String(goal.porcentaje_avance)}%</li>)}</ul></Section><Section title="Retroalimentación compartida"><div className="space-y-3">{authorizedFeedback.length===0?<p className="text-sm text-slate-500">Aún no hay retroalimentaciones habilitadas para compartir.</p>:authorizedFeedback.map(item=><article key={String(item.id)} className="rounded-xl bg-slate-50 p-3 text-sm"><p>{String(item.comentario_entrenador||item.indicacion_tecnica||'Seguimiento registrado')}</p><p className="mt-1"><b>Próximo foco:</b> {String(item.proximo_foco)}</p></article>)}</div></Section><footer className="text-xs text-slate-500">El progreso se compara con el historial de la propia gimnasta. Este informe no constituye una valoración médica.</footer></div>
}
function relation(value:unknown){const item=Array.isArray(value)?value[0]:value;return typeof item==='object'&&item!==null?item as Record<string,unknown>:{} }
function name(value:unknown){const item=Array.isArray(value)?value[0]:value;return typeof item==='object'&&item!==null&&'nombre' in item?String(item.nombre):'—'}
function Metric({label,value}:{label:string;value:string}){return <article className="rounded-2xl border bg-white p-4"><p className="text-xs font-black uppercase text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></article>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="break-inside-avoid rounded-2xl border bg-white p-5"><h2 className="mb-4 text-lg font-black">{title}</h2>{children}</section>}
