import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { getAuthenticatedClub } from '../../../lib/supabase-server'

const competitionSchema=z.object({nombre:z.string().trim().min(1).max(160),fecha:z.string().date()})
const seasonSchema=z.object({id:z.string().uuid().optional(),nombre:z.string().trim().min(3).max(120),fechaInicio:z.string().date(),fechaFin:z.string().date(),competenciaPrincipalNombre:z.string().trim().max(160).nullable(),fechaCompetenciaPrincipal:z.string().date().nullable(),competenciasPreparatorias:z.array(competitionSchema).max(30),objetivoGeneral:z.string().trim().max(1000).nullable(),estado:z.enum(['borrador','activa','cerrada']),groupIds:z.array(z.string().uuid()).min(1)})

async function context(){const ctx=await getAuthenticatedClub();if(ctx.error||!ctx.user||!ctx.clubId)return{...ctx,allowed:false};const {data}=await ctx.supabase.from('perfiles').select('rol').eq('id',ctx.user.id).eq('club_id',ctx.clubId).maybeSingle();return{...ctx,allowed:['administrador','administrador_organizacion','entrenador_principal'].includes(String(data?.rol).toLowerCase())}}

export async function GET(){const ctx=await context();if(!ctx.user||!ctx.clubId)return NextResponse.json({error:'No autenticado'},{status:401});const [seasons,groups,assignments]=await Promise.all([ctx.supabase.from('temporadas').select('*').eq('club_id',ctx.clubId).is('deleted_at',null).order('fecha_inicio',{ascending:false}),ctx.supabase.from('grupos').select('id,nombre,nivel').eq('club_id',ctx.clubId).order('nivel'),ctx.supabase.from('configuracion_grupos').select('grupo_id,temporada_id,heredar_calendario_temporada').not('temporada_id','is',null)]);for(const result of [seasons,groups,assignments])if(result.error)return NextResponse.json({error:result.error.message},{status:500});return NextResponse.json({seasons:seasons.data||[],groups:groups.data||[],assignments:assignments.data||[],canEdit:ctx.allowed})}

export async function POST(request:NextRequest){const ctx=await context();if(!ctx.user||!ctx.clubId)return NextResponse.json({error:'No autenticado'},{status:401});if(!ctx.allowed)return NextResponse.json({error:'No autorizado para administrar temporadas'},{status:403});const parsed=seasonSchema.safeParse(await request.json().catch(()=>({})));if(!parsed.success)return NextResponse.json({error:'Datos de temporada inválidos',details:parsed.error.flatten()},{status:400});const v=parsed.data;if(v.fechaFin<v.fechaInicio||v.fechaCompetenciaPrincipal&&v.fechaCompetenciaPrincipal<v.fechaInicio)return NextResponse.json({error:'Las fechas finales no pueden ser anteriores al inicio'},{status:400});const validGroups=await ctx.supabase.from('grupos').select('id').eq('club_id',ctx.clubId).in('id',v.groupIds);if(validGroups.error||(validGroups.data||[]).length!==v.groupIds.length)return NextResponse.json({error:'Uno o más grupos no pertenecen al club'},{status:403});const seasonPayload={club_id:ctx.clubId,nombre:v.nombre,fecha_inicio:v.fechaInicio,fecha_fin:v.fechaFin,competencia_principal_nombre:v.competenciaPrincipalNombre,fecha_competencia_principal:v.fechaCompetenciaPrincipal,competencias_preparatorias:v.competenciasPreparatorias,objetivo_general:v.objetivoGeneral,estado:v.estado,updated_by:ctx.user.id};let seasonId=v.id;if(seasonId){const {data,error}=await ctx.supabase.from('temporadas').update(seasonPayload).eq('id',seasonId).eq('club_id',ctx.clubId).is('deleted_at',null).select('id').maybeSingle();if(error||!data)return NextResponse.json({error:error?.message||'Temporada no encontrada'},{status:400})}else{const {data,error}=await ctx.supabase.from('temporadas').insert({...seasonPayload,created_by:ctx.user.id}).select('id').single();if(error)return NextResponse.json({error:error.message},{status:400});seasonId=data.id}
const assigned=new Set(v.groupIds);const {data:previous}=await ctx.supabase.from('configuracion_grupos').select('grupo_id').eq('temporada_id',seasonId).eq('heredar_calendario_temporada',true);for(const row of previous||[])if(row.grupo_id&&!assigned.has(row.grupo_id))await ctx.supabase.from('configuracion_grupos').update({temporada_id:null,heredar_calendario_temporada:false}).eq('grupo_id',row.grupo_id).eq('temporada_id',seasonId);for(const groupId of v.groupIds){const {error}=await ctx.supabase.from('configuracion_grupos').upsert({grupo_id:groupId,temporada_id:seasonId,heredar_calendario_temporada:true},{onConflict:'grupo_id'});if(error)return NextResponse.json({error:error.message},{status:400});const existing=await ctx.supabase.from('macrociclos').select('id').eq('grupo_id',groupId).eq('temporada_id',seasonId).is('deleted_at',null).maybeSingle();if(!existing.data)await ctx.supabase.from('macrociclos').insert({club_id:ctx.clubId,temporada_id:seasonId,grupo_id:groupId,nombre:`Plan general - ${v.nombre}`,objetivo:v.objetivoGeneral,anio_temporada:Number(v.fechaInicio.slice(0,4)),fecha_inicio:v.fechaInicio,fecha_fin:v.fechaFin,estado:'borrador',created_by:ctx.user.id,updated_by:ctx.user.id});else await ctx.supabase.from('macrociclos').update({fecha_inicio:v.fechaInicio,fecha_fin:v.fechaFin,objetivo:v.objetivoGeneral,updated_by:ctx.user.id}).eq('id',existing.data.id)}return NextResponse.json({ok:true,seasonId},{status:v.id?200:201})}
