import { AlertTriangle, GitCompareArrows, Link2 } from 'lucide-react'
import ModuleEmptyState from '../../../../components/gymnasts/ModuleEmptyState'
import PlanningTimeline from '../../../../components/gymnasts/PlanningTimeline'
import { getIndividualPlanning,getPlanningTimeline } from '../../../../lib/gymnasts/server'

export default async function IndividualPlanningPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const [planning,timeline]=await Promise.all([getIndividualPlanning(id),getPlanningTimeline(id)])
  if(!planning.plan)return <div className="mx-auto max-w-7xl"><ModuleEmptyState title="Plan individual aún no vinculado" description="Se creará como una referencia al macrociclo del grupo. Solo las adaptaciones se almacenarán de forma individual."/></div>
  return <div className="mx-auto max-w-7xl space-y-6"><header><p className="text-xs font-black uppercase tracking-widest text-indigo-600">Plan general + ajustes</p><h2 className="mt-1 text-2xl font-black">Planificación individual</h2></header>
    {planning.conflicts>0&&<div className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-amber-900"><p className="flex items-center gap-2 font-black"><AlertTriangle className="h-5 w-5"/> {planning.conflicts} cambio(s) requieren confirmación</p><p className="mt-1 text-sm">Las adaptaciones se conservaron y no fueron sobrescritas por el plan general.</p></div>}
    <div className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border bg-white p-5"><Link2 className="text-indigo-600"/><p className="mt-3 text-sm font-bold text-slate-500">Estado</p><p className="text-xl font-black capitalize">{String(planning.plan.estado)}</p></article><article className="rounded-2xl border bg-white p-5"><GitCompareArrows className="text-indigo-600"/><p className="mt-3 text-sm font-bold text-slate-500">Ajustes individuales</p><p className="text-xl font-black">{planning.overrides.length}</p></article><article className="rounded-2xl border bg-white p-5"><AlertTriangle className="text-amber-500"/><p className="mt-3 text-sm font-bold text-slate-500">Conflictos</p><p className="text-xl font-black">{planning.conflicts}</p></article></div>
    <article className="rounded-2xl border bg-white p-6"><h3 className="font-black">Objetivo individual</h3><p className="mt-2 text-sm text-slate-600">{String(planning.plan.objetivo_principal||'Sin objetivo individual definido')}</p></article>
    <PlanningTimeline mesocycles={timeline.mesocycles.map(x=>({id:String(x.id),name:String(x.nombre||'Mesociclo'),start:String(x.fecha_inicio||''),end:String(x.fecha_fin||''),objective:String(x.objetivo||''),volume:x.volumen===null?null:Number(x.volumen),intensity:x.intensidad===null?null:Number(x.intensidad),technical:typeof x.prioridad_tecnica==='string'?x.prioridad_tecnica:null,physical:typeof x.prioridad_fisica==='string'?x.prioridad_fisica:null}))} microcycles={timeline.microcycles.map(x=>({id:String(x.id),mesoId:String(x.mesociclo_id),week:Number(x.numero_semana),type:typeof x.tipo==='string'?x.tipo:null,start:String(x.fecha_inicio),end:String(x.fecha_fin),objective:String(x.objetivo||''),volume:x.volumen===null?null:Number(x.volumen),intensity:x.intensidad===null?null:Number(x.intensidad),deload:Boolean(x.es_descarga),status:String(x.estado)}))} sessions={timeline.sessions.map(x=>({id:String(x.id),date:String(x.fecha_calendario||''),objective:String(x.objetivo),status:String(x.estado),planned:x.duracion_prevista_min===null?null:Number(x.duracion_prevista_min),actual:x.duracion_real_min===null?null:Number(x.duracion_real_min),sourceId:typeof x.sesion_general_id==='string'?x.sesion_general_id:null}))}/>
  </div>
}
