"use client"
import {useState} from 'react'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import {Loader2,Save,UserPlus} from 'lucide-react'

type Group={id:string;nombre:string;nivel:string|null}
export default function GymnastRegistrationForm({groups}:{groups:Group[]}){const router=useRouter();const [form,setForm]=useState({nombre:'',fechaNacimiento:'',grupoId:'',fechaIngreso:new Date().toISOString().slice(0,10)}),[saving,setSaving]=useState(false),[message,setMessage]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);const response=await fetch('/api/gimnastas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const result=await response.json();setMessage(response.ok?'Gimnasta registrada correctamente':result.error||'No se pudo registrar');if(response.ok){setForm({nombre:'',fechaNacimiento:'',grupoId:'',fechaIngreso:new Date().toISOString().slice(0,10)});router.refresh()}setSaving(false)};return <section className="h-fit rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-black text-slate-900"><UserPlus className="h-5 w-5 text-indigo-600"/>Registrar gimnasta</h2><p className="mt-1 text-sm text-slate-600">El nivel se hereda automáticamente del grupo.</p>{groups.length===0?<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Primero debes crear un grupo. <Link href="/configuracion?seccion=grupos" className="font-black underline">Crear grupo</Link></div>:<form onSubmit={submit} className="mt-5 space-y-4"><Field label="Nombre completo"><input required minLength={2} maxLength={160} value={form.nombre} onChange={e=>setForm(v=>({...v,nombre:e.target.value}))} placeholder="Ej. Ana Pérez"/></Field><Field label="Fecha de nacimiento"><input required type="date" max={new Date().toISOString().slice(0,10)} value={form.fechaNacimiento} onChange={e=>setForm(v=>({...v,fechaNacimiento:e.target.value}))}/></Field><Field label="Fecha de ingreso"><input required type="date" value={form.fechaIngreso} onChange={e=>setForm(v=>({...v,fechaIngreso:e.target.value}))}/></Field><Field label="Grupo y nivel"><select required value={form.grupoId} onChange={e=>setForm(v=>({...v,grupoId:e.target.value}))}><option value="">Seleccionar grupo…</option>{groups.map(group=><option key={group.id} value={group.id}>{group.nombre} ({group.nivel||'Sin nivel'})</option>)}</select></Field><button disabled={saving} className="flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 p-3 font-black text-white hover:bg-indigo-700 disabled:opacity-50">{saving?<Loader2 className="h-5 w-5 animate-spin"/>:<Save className="h-5 w-5"/>}Guardar gimnasta</button>{message&&<p role="status" className={`rounded-xl p-3 text-sm font-bold ${message.includes('correctamente')?'bg-emerald-50 text-emerald-800':'bg-rose-50 text-rose-800'}`}>{message}</p>}</form>}<style jsx>{`input,select{width:100%;border:1px solid #cbd5e1;border-radius:.75rem;padding:.75rem;background:#f8fafc;color:#0f172a}`}</style></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1.5 text-xs font-black uppercase tracking-wide text-slate-700">{label}{children}</label>}
