'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { CheckCircle2,Loader2,Pencil,XCircle } from 'lucide-react'
import type { GymnastProfile } from '../../lib/gymnasts/server'

const days=[['lunes','Lunes'],['martes','Martes'],['miercoles','Miércoles'],['jueves','Jueves'],['viernes','Viernes'],['sabado','Sábado'],['domingo','Domingo']] as const

export default function ProfileEditor({gymnast}:{gymnast:GymnastProfile}){
  const router=useRouter();const initialDays=Array.isArray(gymnast.disponibilidad_semanal.dias_entrenamiento)?gymnast.disponibilidad_semanal.dias_entrenamiento.filter((value):value is string=>typeof value==='string'):[]
  const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [message,setMessage]=useState<{kind:'ok'|'error';text:string}|null>(null)
  const [form,setForm]=useState({nombre:gymnast.nombre,fechaNacimiento:gymnast.fecha_nacimiento||'',fechaIngreso:gymnast.fecha_ingreso||'',lateralidad:gymnast.lateralidad||'',categoriaCompetitiva:gymnast.categoria_competitiva||'',diasEntrenamiento:initialDays,duracionSesionHabitualMin:gymnast.duracion_sesion_habitual_min?.toString()||'',objetivoTemporada:gymnast.objetivo_temporada||'',observaciones:gymnast.observaciones||''})
  const update=(key:string,value:string|string[])=>setForm(current=>({...current,[key]:value}))
  const toggleDay=(day:string)=>update('diasEntrenamiento',form.diasEntrenamiento.includes(day)?form.diasEntrenamiento.filter(value=>value!==day):[...form.diasEntrenamiento,day])
  const save=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);setMessage(null);try{const response=await fetch(`/api/gimnastas/${gymnast.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,duracionSesionHabitualMin:form.duracionSesionHabitualMin?Number(form.duracionSesionHabitualMin):null})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'No se pudo guardar');setMessage({kind:'ok',text:'Perfil actualizado'});setOpen(false);router.refresh()}catch(error){setMessage({kind:'error',text:error instanceof Error?error.message:'No se pudo guardar'})}finally{setSaving(false)}}
  return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
    <div className="flex items-start justify-between gap-4"><div><h3 className="font-black text-slate-800">Perfil deportivo</h3><p className="mt-1 text-sm text-slate-500">Información propia de la gimnasta, independiente del macrociclo anual.</p></div><button onClick={()=>setOpen(value=>!value)} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white"><Pencil className="h-4 w-4"/>{open?'Cerrar':'Editar perfil'}</button></div>
    {message&&<p className={`mt-4 flex items-center gap-2 rounded-xl p-3 text-sm font-bold ${message.kind==='ok'?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-700'}`}>{message.kind==='ok'?<CheckCircle2 className="h-4 w-4"/>:<XCircle className="h-4 w-4"/>}{message.text}</p>}
    {!open?<dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Categoría" value={gymnast.categoria_competitiva}/><Info label="Lateralidad" value={gymnast.lateralidad}/><Info label="Días disponibles" value={initialDays.length?String(initialDays.length):null}/><Info label="Duración habitual" value={gymnast.duracion_sesion_habitual_min?`${gymnast.duracion_sesion_habitual_min} min`:null}/></dl>:
    <form onSubmit={save} className="mt-6 space-y-7"><fieldset className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 text-sm font-black uppercase tracking-wider text-slate-500">Información general</legend><Field label="Nombre completo"><input required value={form.nombre} onChange={e=>update('nombre',e.target.value)} className="input"/></Field><Field label="Fecha de nacimiento"><input type="date" value={form.fechaNacimiento} onChange={e=>update('fechaNacimiento',e.target.value)} className="input"/></Field><Field label="Fecha de ingreso"><input type="date" value={form.fechaIngreso} onChange={e=>update('fechaIngreso',e.target.value)} className="input"/></Field><Field label="Categoría competitiva"><input value={form.categoriaCompetitiva} onChange={e=>update('categoriaCompetitiva',e.target.value)} className="input"/></Field><Field label="Lateralidad"><select value={form.lateralidad} onChange={e=>update('lateralidad',e.target.value)} className="input"><option value="">Sin registrar</option><option value="diestra">Diestra</option><option value="zurda">Zurda</option><option value="ambidiestra">Ambidiestra</option></select></Field><Field label="Duración habitual (min)"><input type="number" min="1" max="720" value={form.duracionSesionHabitualMin} onChange={e=>update('duracionSesionHabitualMin',e.target.value)} className="input"/></Field></fieldset>
      <fieldset><legend className="mb-3 text-sm font-black uppercase tracking-wider text-slate-500">Disponibilidad semanal</legend><div className="flex flex-wrap gap-2">{days.map(([value,label])=><button type="button" key={value} onClick={()=>toggleDay(value)} className={`rounded-full border px-4 py-2 text-sm font-bold ${form.diasEntrenamiento.includes(value)?'border-indigo-600 bg-indigo-50 text-indigo-700':'border-slate-200 text-slate-500'}`}>{label}</button>)}</div></fieldset>
      <fieldset className="grid gap-4"><legend className="mb-1 text-sm font-black uppercase tracking-wider text-slate-500">Temporada y observaciones</legend><Field label="Objetivo principal de temporada"><textarea rows={3} value={form.objetivoTemporada} onChange={e=>update('objetivoTemporada',e.target.value)} className="input"/></Field><Field label="Observaciones del entrenador"><textarea rows={3} value={form.observaciones} onChange={e=>update('observaciones',e.target.value)} className="input"/></Field></fieldset>
      <button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-black text-white disabled:opacity-60">{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Guardar perfil individual</button><style jsx>{`.input{width:100%;border:1px solid #cbd5e1;border-radius:.75rem;padding:.7rem .8rem;outline:none;background:#f8fafc}.input:focus{border-color:#4f46e5;box-shadow:0 0 0 2px #e0e7ff}`}</style>
    </form>}
  </section>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1.5 text-sm font-bold text-slate-700"><span>{label}</span>{children}</label>}
function Info({label,value}:{label:string;value:string|null}){return <div><dt className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</dt><dd className="mt-1 text-sm font-bold capitalize text-slate-700">{value||'Sin registrar'}</dd></div>}
