'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { BookOpenCheck, Plus, ShieldCheck } from 'lucide-react'

type Source={id:string;title:string;organization:string;version:string|null;validity:string;usageScope:string;owned:boolean}
type Stage={id:string;name:string;order:number;description:string|null;owned:boolean}
type Rule={id:string;title:string;category:string;actionLevel:string;status:string;sourceTitle:string;owned:boolean}

export default function SportsGovernanceManager({sources,stages,rules}:{sources:Source[];stages:Stage[];rules:Rule[]}) {
  const router=useRouter()
  const [mode,setMode]=useState<'source'|'stage'|'rule'>('rule')
  const [message,setMessage]=useState('')
  const [busy,setBusy]=useState(false)
  const [form,setForm]=useState({code:'',title:'',organization:'',version:'',year:'',validity:'pendiente_revision',usageScope:'solo_referencia',sourceUrl:'',licenseNote:'',order:'1',description:'',minAge:'',maxAge:'',objectives:'',sourceId:'',stageId:'',category:'desarrollo',actionLevel:'informativa',condition:'{}',recommendation:'{"acciones":[]}',rationale:'',referencePages:''})
  const set=(key:string,value:string)=>setForm(current=>({...current,[key]:value}))
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setMessage('');let body:Record<string,unknown>
    try {
      body=mode==='source'?{kind:mode,code:form.code,title:form.title,organization:form.organization,version:form.version||null,publicationYear:form.year?Number(form.year):null,validity:form.validity,usageScope:form.usageScope,sourceUrl:form.sourceUrl||null,licenseNote:form.licenseNote}
        :mode==='stage'?{kind:mode,code:form.code,name:form.title,order:Number(form.order),description:form.description,referenceMinAge:form.minAge?Number(form.minAge):null,referenceMaxAge:form.maxAge?Number(form.maxAge):null,objectives:form.objectives.split('\n').map(value=>value.trim()).filter(Boolean)}
        :{kind:mode,code:form.code,title:form.title,sourceId:form.sourceId,stageId:form.stageId||null,category:form.category,actionLevel:form.actionLevel,condition:JSON.parse(form.condition),recommendation:JSON.parse(form.recommendation),rationale:form.rationale,referencePages:form.referencePages||null}
    } catch {setMessage('La condición o recomendación no contiene JSON válido.');return}
    setBusy(true);const response=await fetch('/api/gobernanza-deportiva',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json() as {error?:string};setBusy(false);setMessage(response.ok?'Registro creado. Las reglas nuevas permanecen en borrador hasta su aprobación.':result.error||'No fue posible guardar');if(response.ok)router.refresh()}
  const changeStatus=async(id:string,status:string)=>{setBusy(true);const response=await fetch('/api/gobernanza-deportiva',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'rule',id,status})});const result=await response.json() as {error?:string};setBusy(false);setMessage(response.ok?'Estado de la regla actualizado.':result.error||'No fue posible actualizar');if(response.ok)router.refresh()}

  return <section className="space-y-5 rounded-2xl border border-violet-200 bg-white p-5 text-slate-950">
    <header className="flex items-start gap-3"><BookOpenCheck className="mt-1 h-6 w-6 text-violet-700"/><div><h2 className="text-lg font-black">Gobernanza del conocimiento deportivo</h2><p className="text-sm text-slate-600">Fuentes versionadas, etapas y reglas trazables. Solo las reglas aprobadas pueden alimentar al asistente.</p></div></header>
    <div className="flex flex-wrap gap-2">{(['source','stage','rule'] as const).map(item=><button type="button" key={item} onClick={()=>setMode(item)} className={`rounded-lg px-3 py-2 text-sm font-bold ${mode===item?'bg-violet-700 text-white':'bg-slate-100'}`}>{item==='source'?'Nueva fuente':item==='stage'?'Nueva etapa':'Nueva regla'}</button>)}</div>
    <form onSubmit={submit} className="grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-2 xl:grid-cols-3">
      <Field label="Código estable"><input required pattern="[a-z0-9_-]+" value={form.code} onChange={e=>set('code',e.target.value)}/></Field>
      <Field label={mode==='stage'?'Nombre de la etapa':'Título'}><input required value={form.title} onChange={e=>set('title',e.target.value)}/></Field>
      {mode==='source'&&<><Field label="Organización"><input required value={form.organization} onChange={e=>set('organization',e.target.value)}/></Field><Field label="Versión"><input value={form.version} onChange={e=>set('version',e.target.value)}/></Field><Field label="Año"><input type="number" min="1900" max="2200" value={form.year} onChange={e=>set('year',e.target.value)}/></Field><Field label="Vigencia"><select value={form.validity} onChange={e=>set('validity',e.target.value)}><option value="pendiente_revision">Pendiente de revisión</option><option value="vigente">Vigente</option><option value="historica">Histórica</option><option value="retirada">Retirada</option></select></Field><Field label="Permiso de uso"><select value={form.usageScope} onChange={e=>set('usageScope',e.target.value)}><option value="solo_referencia">Solo referencia</option><option value="extractos_licenciados">Extractos licenciados</option><option value="uso_interno_completo">Uso interno completo</option></select></Field><Field label="URL"><input type="url" value={form.sourceUrl} onChange={e=>set('sourceUrl',e.target.value)}/></Field><Field label="Licencia y límites" wide><textarea required value={form.licenseNote} onChange={e=>set('licenseNote',e.target.value)}/></Field></>}
      {mode==='stage'&&<><Field label="Orden"><input required type="number" min="1" max="100" value={form.order} onChange={e=>set('order',e.target.value)}/></Field><Field label="Edad mínima orientativa"><input type="number" min="0" step="0.5" value={form.minAge} onChange={e=>set('minAge',e.target.value)}/></Field><Field label="Edad máxima orientativa"><input type="number" min="0" step="0.5" value={form.maxAge} onChange={e=>set('maxAge',e.target.value)}/></Field><Field label="Descripción" wide><textarea required value={form.description} onChange={e=>set('description',e.target.value)}/></Field><Field label="Objetivos (uno por línea)" wide><textarea value={form.objectives} onChange={e=>set('objectives',e.target.value)}/></Field></>}
      {mode==='rule'&&<><Field label="Fuente"><select required value={form.sourceId} onChange={e=>set('sourceId',e.target.value)}><option value="">Seleccionar</option>{sources.map(source=><option key={source.id} value={source.id}>{source.title}</option>)}</select></Field><Field label="Etapa opcional"><select value={form.stageId} onChange={e=>set('stageId',e.target.value)}><option value="">Todas</option>{stages.map(stage=><option key={stage.id} value={stage.id}>{stage.name}</option>)}</select></Field><Field label="Categoría"><select value={form.category} onChange={e=>set('category',e.target.value)}>{['desarrollo','seguridad','carga','tecnica','recuperacion','bienestar','competencia','inclusion'].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Nivel de acción"><select value={form.actionLevel} onChange={e=>set('actionLevel',e.target.value)}><option value="informativa">Informativa</option><option value="precaucion">Precaución</option><option value="bloqueo">Bloqueo</option></select></Field><Field label="Condición (JSON)" wide><textarea required value={form.condition} onChange={e=>set('condition',e.target.value)}/></Field><Field label="Recomendación (JSON)" wide><textarea required value={form.recommendation} onChange={e=>set('recommendation',e.target.value)}/></Field><Field label="Fundamento" wide><textarea required value={form.rationale} onChange={e=>set('rationale',e.target.value)}/></Field><Field label="Páginas de referencia"><input value={form.referencePages} onChange={e=>set('referencePages',e.target.value)}/></Field></>}
      <button disabled={busy} className="self-end rounded-xl bg-violet-700 p-3 font-bold text-white disabled:opacity-40"><Plus className="mr-2 inline h-4 w-4"/>{busy?'Guardando…':'Crear registro'}</button>
      {message&&<p role="status" className="self-center text-sm font-bold md:col-span-2">{message}</p>}
    </form>
    <div className="grid gap-5 xl:grid-cols-3">
      <List title="Fuentes" rows={sources.map(item=>({id:item.id,title:item.title,meta:`${item.organization} · ${item.version||'sin versión'} · ${item.validity} · ${item.usageScope}`,owned:item.owned}))}/>
      <List title="Etapas" rows={stages.map(item=>({id:item.id,title:`${item.order}. ${item.name}`,meta:`${item.description||'Sin descripción'} · ${item.owned?'Club':'Global'}`,owned:item.owned}))}/>
      <article className="rounded-xl border p-4"><h3 className="font-black">Reglas</h3><div className="mt-3 max-h-96 space-y-2 overflow-auto">{rules.map(rule=><div key={rule.id} className="rounded-lg bg-slate-50 p-3"><div className="flex items-start justify-between gap-2"><div><b className="text-sm">{rule.title}</b><p className="text-xs text-slate-600">{rule.category} · {rule.actionLevel} · {rule.sourceTitle}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-black ${rule.status==='aprobada'?'bg-emerald-100 text-emerald-800':'bg-amber-100 text-amber-800'}`}>{rule.status}</span></div>{rule.owned&&<div className="mt-2 flex gap-2"><button disabled={busy} onClick={()=>changeStatus(rule.id,'en_revision')} className="rounded border px-2 py-1 text-xs font-bold">Revisar</button><button disabled={busy} onClick={()=>changeStatus(rule.id,'aprobada')} className="rounded bg-emerald-700 px-2 py-1 text-xs font-bold text-white"><ShieldCheck className="mr-1 inline h-3 w-3"/>Aprobar</button><button disabled={busy} onClick={()=>changeStatus(rule.id,'retirada')} className="rounded border px-2 py-1 text-xs font-bold text-rose-700">Retirar</button></div>}</div>)}</div></article>
    </div>
  </section>
}

function Field({label,wide=false,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={`grid gap-1 text-sm font-bold ${wide?'md:col-span-2 xl:col-span-3':''}`}>{label}<span className="contents [&_input]:rounded-xl [&_input]:border [&_input]:bg-white [&_input]:p-3 [&_select]:rounded-xl [&_select]:border [&_select]:bg-white [&_select]:p-3 [&_textarea]:min-h-24 [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:bg-white [&_textarea]:p-3">{children}</span></label>}
function List({title,rows}:{title:string;rows:Array<{id:string;title:string;meta:string;owned:boolean}>}){return <article className="rounded-xl border p-4"><h3 className="font-black">{title}</h3><div className="mt-3 max-h-96 space-y-2 overflow-auto">{rows.map(row=><div key={row.id} className="rounded-lg bg-slate-50 p-3"><b className="text-sm">{row.title}</b><p className="text-xs text-slate-600">{row.meta}</p><span className="text-[10px] font-black uppercase text-violet-700">{row.owned?'Organización':'Global'}</span></div>)}</div></article>}
